### ISSUE TITLE
Game stuck when giving the correct word

### ISSUE THREAD

**Issue by Hafplo** [jakerella/guessle#15]
After playing several consecutive games, when giving the correct word and pressing 'guess' nothing happens.
If I give a wrong word, or anything else, the 'guess' button does react.
After pressing, and refreshing, and pressing several times - sometimes it continues

**Comment by jakerella** [comment]
Yeah, this is related to #10. Basically, ever once in a while the redis connection fails and then the "guess" fails. I've tried a number of things and can't get the redis connections to stop maxing out...

**Comment by jakerella** [comment]
I added some better error handling around the global stats collection (which tends to be the culprit for high numbers of redis connections). Hopefully this will at least let play continue when the connections max out.
