### ISSUE TITLE
Fix feedback with double letters

### ISSUE THREAD

**Issue by eibanez** [jakerella/guessle#9]
Hi! Cool version. I have a small “bug”. 

The word was BLUNT and guessed BULLS.

The app highlighted both Ls with yellow, but I would expect to only have one highlighted.

Great work!

**Comment by jakerella** [comment]
Thanks!

Yeah, I've noticed that as well and I've been thinking about it. I don't have a great solution. Basically it comes down to which "L" I would highlight as yellow? And would it be more or less confusing if it was the first "L" or the second "L"? In the end, I went with indecision and left them both yellow... need to think more about this.

**Comment by eibanez** [comment]
Because the position doesn't matter, I'd highlight the first one.

**Comment by jakerella** [comment]
Ok, this should be fixed.

**Comment by eibanez** [comment]
Thank you!
